# Generated by Django 4.2.6 on 2023-11-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0002_caso_especialidad_cliente_abogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
