# Generated by Django 4.2.6 on 2023-12-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0003_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='materia',
            field=models.CharField(choices=[('laboral', 'Laboral'), ('civilComercial', 'Civil y Comercial'), ('administrativo', 'Administrativo'), ('penal', 'Penal'), ('ninezAdolecencia', 'Niñez y Adolecencia')], default='laboral', max_length=20),
        ),
    ]
