# Generated by Django 4.2.6 on 2023-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0004_alter_caso_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='materia',
            field=models.CharField(choices=[('laboral', 'Laboral'), ('civil y comercial', 'Civil y Comercial'), ('administrativo', 'Administrativo'), ('penal', 'Penal'), ('niñez y adolecencia', 'Niñez y Adolecencia')], default='laboral', max_length=20),
        ),
    ]
