# Generated by Django 4.2.6 on 2023-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0005_alter_caso_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abogado',
            name='cliente_relacionado',
        ),
        migrations.RemoveField(
            model_name='abogado',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='abogado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
