# Generated by Django 4.2.6 on 2023-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0006_remove_abogado_cliente_relacionado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.AddField(
            model_name='abogado',
            name='especilidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
