# Generated by Django 4.2.6 on 2023-12-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ley_en_mano', '0007_delete_especialidad_abogado_especilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogado',
            old_name='especilidad',
            new_name='especialidad',
        ),
    ]
